import fs from "node:fs";
import path from "node:path";
import type { Project, Area, TestSuite } from "./project.js";

/**
 * Renders the `.agents/` tree an agent navigates by.
 *
 * Two rules shape everything here:
 *
 *  - Index-shaped, not prose-shaped. The job of these files is to answer
 *    "where is X?" without a search. Prose costs tokens to read and still
 *    leaves the agent inferring.
 *  - Generated, never hand-edited. A map that drifts points agents at files
 *    that moved, which is the exact failure this is meant to prevent.
 */

export interface EmittedFile {
  /** Relative to repo root. */
  path: string;
  content: string;
}

const rel = (p: string) => (p === "" ? "(repo root)" : p);

function table(rows: string[][], headers: string[]): string {
  const head = `| ${headers.join(" | ")} |`;
  const sep = `|${headers.map(() => "---").join("|")}|`;
  const body = rows.map((r) => `| ${r.join(" | ")} |`).join("\n");
  return [head, sep, body].join("\n");
}

const GENERATED_BANNER = (name: string) =>
  `<!-- Generated by \`pp init\`. Do not edit by hand — regenerate instead. -->\n\n` +
  `> Regenerate with \`pp init --refresh\`. A stale map points agents at files\n` +
  `> that moved, which costs more than having no map at all.\n\n`;

// --- README ---------------------------------------------------------------

function readme(p: Project): string {
  const areaRows = p.areas.map((a) => [
    `\`${rel(a.dir)}\``,
    a.kind,
    a.stack.length ? a.stack.join(", ") : "—",
    String(a.files.length),
  ]);

  return (
    `# Agent guide — ${p.name}\n\n` +
    GENERATED_BANNER(p.name) +
    `**Read this before starting work in this repository.**\n\n` +
    `## Rules that apply to every task\n\n` +
    `1. Do not explore the repository to find things. Use the maps below — they\n` +
    `   list files and line numbers. If something is not in them, ask rather\n` +
    `   than searching.\n` +
    `2. Stay inside the files named in your task. If the work appears to require\n` +
    `   touching others, stop and ask first.\n` +
    `3. Follow the test discipline in [map/tests.md](map/tests.md). It exists\n` +
    `   because test runs are billed time and agents iterate.\n` +
    `4. Do not reformat, rename, or refactor anything outside the stated scope.\n` +
    `5. Do not upgrade, add, or remove dependencies unless that is the task.\n\n` +
    `## Where things are\n\n` +
    (areaRows.length
      ? table(areaRows, ["Area", "Kind", "Stack", "Files"]) + "\n\n"
      : "_No distinct areas detected._\n\n") +
    `## Maps\n\n` +
    `| Map | Use it when |\n|---|---|\n` +
    `| [map/overview.md](map/overview.md) | Orienting; finding which area owns something |\n` +
    `| [map/backend.md](map/backend.md) | Touching server code, routes, or models |\n` +
    `| [map/frontend.md](map/frontend.md) | Touching UI, components, or client routes |\n` +
    `| [map/tests.md](map/tests.md) | **Before running any test.** Always. |\n\n` +
    `## Writing work items\n\n` +
    `Use [work-items/template.md](work-items/template.md). A work item with every\n` +
    `field filled and no open questions is ready for an agent; one with open\n` +
    `questions is not.\n\n` +
    (p.offLimits.length
      ? `## Do not modify\n\n` +
        p.offLimits.map((d) => `- \`${d}\``).join("\n") +
        `\n\nThese are generated or vendored. Change the source, not the output.\n\n`
      : "")
  );
}

// --- overview -------------------------------------------------------------

function overview(p: Project): string {
  const entryPoints = p.index.files
    .filter((f) =>
      /(^|\/)(main|index|app|server|cli|__main__|wsgi|asgi|manage)\.(ts|tsx|js|jsx|py)$/.test(f),
    )
    .slice(0, 20);

  return (
    `# Overview — ${p.name}\n\n` +
    GENERATED_BANNER(p.name) +
    `${p.index.files.length} files indexed, ${p.index.symbols.length} symbols.\n\n` +
    `## Areas\n\n` +
    (p.areas.length
      ? table(
          p.areas.map((a) => [`\`${rel(a.dir)}\``, a.kind, a.stack.join(", ") || "—", String(a.files.length)]),
          ["Directory", "Kind", "Stack", "Files"],
        )
      : "_none detected_") +
    `\n\n## Entry points\n\n` +
    (entryPoints.length ? entryPoints.map((f) => `- \`${f}\``).join("\n") : "_none detected_") +
    `\n\n## Conventions\n\n` +
    (p.conventions.length ? p.conventions.map((c) => `- ${c}`).join("\n") : "_none detected_") +
    `\n\n## Needs a human\n\n` +
    p.unknowns.map((u) => `- [ ] ${u}`).join("\n") +
    `\n`
  );
}

// --- backend --------------------------------------------------------------

function backend(p: Project): string {
  const areas = p.areas.filter((a) => a.kind === "backend");
  const routeRows = p.routes
    .filter((r) => r.method !== "PAGE")
    .slice(0, 200)
    .map((r) => [`\`${r.method}\``, `\`${r.path}\``, `${r.file}:${r.line}`]);
  const modelRows = p.models.map((m) => [`\`${m.name}\``, m.kind, `${m.file}:${m.line}`]);

  const modules = areas
    .flatMap((a) => a.files)
    .filter((f) => f.endsWith(".py") && !/test/i.test(f))
    .slice(0, 250);

  return (
    `# Backend map — ${p.name}\n\n` +
    GENERATED_BANNER(p.name) +
    `## HTTP routes\n\n` +
    (routeRows.length ? table(routeRows, ["Method", "Path", "Defined at"]) : "_none detected_") +
    `\n\n## Data models\n\n` +
    (modelRows.length ? table(modelRows, ["Model", "Kind", "Defined at"]) : "_none detected_") +
    `\n\n## Modules\n\n` +
    (modules.length ? modules.map((f) => `- \`${f}\``).join("\n") : "_none detected_") +
    `\n`
  );
}

// --- frontend -------------------------------------------------------------

function frontend(p: Project): string {
  const pageRows = p.routes
    .filter((r) => r.method === "PAGE")
    .slice(0, 200)
    .map((r) => [`\`${r.path}\``, `${r.file}:${r.line}`]);
  const compRows = p.components.map((c) => [`\`${c.name}\``, `${c.file}:${c.line}`]);

  return (
    `# Frontend map — ${p.name}\n\n` +
    GENERATED_BANNER(p.name) +
    `## Client routes\n\n` +
    (pageRows.length ? table(pageRows, ["Path", "Defined at"]) : "_none detected_") +
    `\n\n## Components\n\n` +
    (compRows.length ? table(compRows, ["Component", "Defined at"]) : "_none detected_") +
    `\n`
  );
}

// --- the test map ---------------------------------------------------------

function tests(p: Project): string {
  const unit = p.tests.filter((t) => t.kind === "unit");
  const integration = p.tests.filter((t) => t.kind === "integration");
  const e2e = p.tests.filter((t) => t.kind === "e2e");

  const suiteBlock = (label: string, suites: TestSuite[]) =>
    suites.length
      ? `${table(
          suites.map((s) => [s.runner, `\`${s.command}\``, s.dirs.map((d) => `\`${d}\``).join(" "), String(s.fileCount)]),
          ["Runner", "Command", "Where", "Files"],
        )}\n\n`
      : `_no ${label} suite detected_\n\n`;

  return (
    `# Test map — ${p.name}\n\n` +
    GENERATED_BANNER(p.name) +
    `**Read this before running anything.**\n\n` +
    `Agent time is billed by the minute and agents iterate. A full suite run per\n` +
    `iteration is the single most expensive habit an agent can have, and an E2E\n` +
    `suite is the worst case of it.\n\n` +
    `## The discipline\n\n` +
    `1. **After each change** — run only the unit tests covering the files you\n` +
    `   touched. Narrow to a path or a single test id.\n` +
    `2. **When you believe you are done** — run the integration tests for the\n` +
    `   area you changed. Once.\n` +
    `3. **E2E** — only if the change alters a user-visible flow, and then only\n` +
    `   once, at the very end. Never per iteration, never to check a single edit.\n` +
    `4. **Never run the whole suite to validate one edit.**\n` +
    `5. If a test fails in a way unrelated to your change, stop and report it\n` +
    `   rather than fixing the test.\n\n` +
    `## Unit — run these freely\n\n` +
    suiteBlock("unit", unit) +
    `## Integration — run once, when you think you are done\n\n` +
    suiteBlock("integration", integration) +
    `## E2E — ration these\n\n` +
    suiteBlock("e2e", e2e) +
    `## Known flaky tests\n\n` +
    `_None recorded._ Flakiness cannot be detected from source. Add any known\n` +
    `flaky specs here — without this list an agent will chase a failure that was\n` +
    `never real, or "fix" a test that was not broken.\n\n` +
    `| Test | Why it flakes | What to do |\n|---|---|---|\n| | | |\n\n` +
    `## Cost\n\n` +
    `_Not measured._ Time one full run of each suite and record it below. These\n` +
    `numbers decide how strictly E2E should be rationed.\n\n` +
    `| Suite | Wall-clock |\n|---|---|\n` +
    p.tests.map((t) => `| ${t.runner} (${t.kind}) | |`).join("\n") +
    `\n`
  );
}

// --- work item template ---------------------------------------------------

function workItemTemplate(p: Project): string {
  const verify = p.tests.find((t) => t.kind === "unit")?.command ?? "<command>";
  return (
    `# Work item template\n\n` +
    GENERATED_BANNER(p.name) +
    `Paste this into a GitLab work item. A work item with every field filled and\n` +
    `**no open questions** is ready for an agent. One with open questions is not —\n` +
    `answer them first, because a question you answer costs seconds and the same\n` +
    `question answered by an agent searching the repo costs real money.\n\n` +
    `---\n\n` +
    `## Objective\n\n` +
    `_One sentence. The concrete change, not the motivation._\n\n` +
    `## Area\n\n` +
    `_Which area, and the map chunk covering it (e.g. \`.agents/map/backend.md\`)._\n\n` +
    `## Files in scope\n\n` +
    `- \`path/to/file.py\`\n\n` +
    `_Explicit paths only. Never guess one — a wrong path costs more than a\n` +
    `missing one, because the agent hunts for a file that does not exist._\n\n` +
    `## Steps\n\n` +
    `1. \n\n` +
    `## Constraints\n\n` +
    `- Follow the patterns already in the touched files.\n\n` +
    `## Do NOT\n\n` +
    `- Do not modify files outside the list above.\n` +
    `- Do not reformat, rename, or refactor unrelated code.\n` +
    `- Do not upgrade, add, or remove dependencies.\n` +
    `- Do not broaden test coverage beyond what this change requires.\n\n` +
    `## Done when\n\n` +
    `- \n\n` +
    `## Verify with\n\n` +
    `\`\`\`\n${verify}\n\`\`\`\n\n` +
    `_See [../map/tests.md](../map/tests.md) before running anything._\n\n` +
    `## Open questions\n\n` +
    `_Anything genuinely unknown. Ask — do not explore to resolve it._\n\n` +
    `- [ ] \n`
  );
}

// --- Devin setup ----------------------------------------------------------

function devinSetup(p: Project): string {
  const installs: string[] = [];
  if (p.areas.some((a) => a.stack.includes("typescript") || a.kind === "frontend")) {
    installs.push("npm ci   # or the workspace equivalent");
  }
  if (p.areas.some((a) => a.kind === "backend")) {
    installs.push("pip install -r requirements.txt   # or: uv sync / poetry install");
  }
  if (p.tests.some((t) => t.runner === "playwright")) {
    installs.push("npx playwright install --with-deps   # browsers are slow to fetch; bake them in");
  }

  return (
    `# Devin setup — ${p.name}\n\n` +
    GENERATED_BANNER(p.name) +
    `A one-time setup that removes cost from every future session.\n\n` +
    `## 1. Machine snapshot\n\n` +
    `Setup is a fixed cost paid on **every** session unless snapshotted. If the\n` +
    `install and build take eight minutes, that is roughly half an ACU per\n` +
    `session spent rebuilding what was already built.\n\n` +
    `Run these, confirm the project builds, then save the snapshot:\n\n` +
    "```bash\n" +
    (installs.length ? installs.join("\n") : "# add install steps here") +
    "\n```\n\n" +
    `Re-snapshot when dependencies change materially. A stale snapshot that\n` +
    `fails to build is worse than none — the agent then debugs the environment.\n\n` +
    `## 2. Knowledge entries\n\n` +
    `Add these at **app.devin.ai → Settings → Knowledge**.\n\n` +
    `### Always read the agent guide first\n\n` +
    `**Trigger:** every session in this repository.\n\n` +
    "```\n" +
    `Before doing anything in ${p.name}, read .agents/README.md, then the map for\n` +
    `the area you are touching (.agents/map/). These list files and line numbers.\n` +
    `Do not search the repository for something the maps already name.\n\n` +
    `Before running any test, read .agents/map/tests.md and follow its rules.\n` +
    "```\n\n" +
    `### Scope discipline\n\n` +
    `**Trigger:** every session.\n\n` +
    "```\n" +
    `Stay inside the files named in the task. If the work seems to require others,\n` +
    `stop and ask. Do not reformat, rename, or refactor unrelated code. Do not\n` +
    `change dependencies unless that is the task. If a required detail is missing,\n` +
    `ask rather than exploring the repository to resolve it.\n` +
    "```\n\n" +
    (p.offLimits.length
      ? `### Do not modify\n\n**Trigger:** before editing any file.\n\n` +
        "```\nNever modify files under:\n" +
        p.offLimits.map((d) => `- ${d}`).join("\n") +
        `\nThese are generated or vendored. Change the source, not the output.\n` +
        "```\n\n"
      : "") +
    `## 3. Keep it fresh\n\n` +
    `Wire \`pp init --refresh\` into CI on merge to main. The maps are only worth\n` +
    `trusting if they cannot drift.\n`
  );
}

// --- root pointer ---------------------------------------------------------

function agentsPointer(p: Project): string {
  return (
    `# ${p.name}\n\n` +
    `Agent instructions live in [\`.agents/README.md\`](.agents/README.md).\n\n` +
    `Read it before starting work. It contains the codebase maps, the test\n` +
    `discipline, and the work item contract.\n\n` +
    `<!-- Generated by \`pp init\`. -->\n`
  );
}

// --- assembly -------------------------------------------------------------

export function emitAgentFiles(p: Project): EmittedFile[] {
  return [
    { path: ".agents/README.md", content: readme(p) },
    { path: ".agents/map/overview.md", content: overview(p) },
    { path: ".agents/map/backend.md", content: backend(p) },
    { path: ".agents/map/frontend.md", content: frontend(p) },
    { path: ".agents/map/tests.md", content: tests(p) },
    { path: ".agents/work-items/template.md", content: workItemTemplate(p) },
    { path: ".agents/devin-setup.md", content: devinSetup(p) },
    { path: "AGENTS.md", content: agentsPointer(p) },
  ];
}

export function writeFiles(root: string, files: EmittedFile[]): void {
  for (const f of files) {
    const full = path.join(root, f.path);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, f.content);
  }
}
