import type { Config, RepoProfile } from "./config.js";

/**
 * Devin Knowledge entries.
 *
 * PP's repo profiles and standing constraints are the same information Devin
 * re-derives at the start of every session. Held only in ~/.pp/config.json
 * they help exactly one prompt at a time; as Knowledge they apply to every
 * session forever, including ones started from Slack, a Linear ticket, or the
 * API — which PP never sees.
 *
 * Orientation is a fixed cost. This is how you stop paying it repeatedly.
 */
export interface KnowledgeEntry {
  title: string;
  /** Devin scopes Knowledge per repo; null means org-wide. */
  scope: string | null;
  /** When Devin should apply it. */
  trigger: string;
  body: string;
}

export function buildKnowledge(cfg: Config): KnowledgeEntry[] {
  const entries: KnowledgeEntry[] = [];

  if (cfg.standingConstraints.length) {
    entries.push({
      title: "Scope discipline for all sessions",
      scope: null,
      trigger: "Always — applies to every session in this organization.",
      body: [
        "Follow these rules on every task:",
        "",
        ...cfg.standingConstraints.map((c) => `- ${c}`),
        "",
        "If a required detail is missing or an assumption proves wrong, stop and ask.",
        "Do not explore the repository to resolve it on your own — asking is faster and cheaper than searching.",
      ].join("\n"),
    });
  }

  for (const repo of cfg.repos) {
    entries.push(...repoEntries(repo));
  }

  return entries;
}

function repoEntries(repo: RepoProfile): KnowledgeEntry[] {
  const out: KnowledgeEntry[] = [];

  if (repo.testCommand) {
    out.push({
      title: `How to verify changes in ${repo.name}`,
      scope: repo.name,
      trigger: `When verifying any change in the ${repo.name} repository.`,
      body: [
        `Verify with: \`${repo.testCommand}\``,
        "",
        "Scope the run to the tests covering your change rather than the whole suite.",
        "Test runs bill as VM time on every iteration, so run the full suite at most once, at the end.",
      ].join("\n"),
    });
  }

  if (repo.conventions?.length) {
    out.push({
      title: `Conventions in ${repo.name}`,
      scope: repo.name,
      trigger: `When writing or modifying code in the ${repo.name} repository.`,
      body: [
        `Follow the existing conventions in ${repo.name}:`,
        "",
        ...repo.conventions.map((c) => `- ${c}`),
        "",
        "Match the patterns already present in the files you touch.",
        "Do not introduce a new library or abstraction when an established one already covers the case.",
      ].join("\n"),
    });
  }

  if (repo.offLimits?.length) {
    out.push({
      title: `Directories not to modify in ${repo.name}`,
      scope: repo.name,
      trigger: `Before editing any file in the ${repo.name} repository.`,
      body: [
        "Never modify files under these paths:",
        "",
        ...repo.offLimits.map((d) => `- \`${d}\``),
        "",
        "If a task appears to require changing one of them, stop and ask first.",
      ].join("\n"),
    });
  }

  return out;
}

/** Paste-ready markdown, one block per Knowledge entry. */
export function renderKnowledge(entries: KnowledgeEntry[]): string {
  if (!entries.length) {
    return [
      "No knowledge to export yet.",
      "",
      "Add repo profiles to ~/.pp/config.json first — testCommand, conventions,",
      "and offLimits each become a Knowledge entry. See `pp --config`.",
      "",
    ].join("\n");
  }

  const header = [
    "# Devin Knowledge — generated by PP",
    "",
    `${entries.length} entr${entries.length === 1 ? "y" : "ies"}. Add each one at`,
    "app.devin.ai → Settings → Knowledge, using the title and scope shown.",
    "",
    "Keep these accurate. Stale Knowledge is worse than none — it sends Devin",
    "down trial-and-error paths that cost more than having no context at all.",
    "",
    "---",
    "",
  ].join("\n");

  const blocks = entries.map((e) =>
    [
      `## ${e.title}`,
      "",
      `**Scope:** ${e.scope ?? "all repositories"}`,
      `**Trigger:** ${e.trigger}`,
      "",
      "```",
      e.body,
      "```",
      "",
    ].join("\n"),
  );

  return header + blocks.join("\n---\n\n");
}
